spring:
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximumPoolSize: 50
  jpa:
    properties:
      hibernate:
        type: TRACE
        generate-statistics: true
        show-sql: true
        format-sql: true
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
    show-sql: true
  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: true
  mvc:
    async:
      requestTimeout: 150000
  main:
    allowCircularReferences: true
  sleuth:
    annotation:
      enabled: true
      sampler:
        probability: 1.0

server:
  port: ${APPLICATION_PORT}

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        security: DEBUG
        data:
          elasticsearch:
            core: ERROR
            # client:
            #   WIRE: trace
    # com:
    #   netflix:
    #     discovery: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

data:
  seed:
    enabled: false


login:
  url:
    path: /users/login

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 360000000
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true # Indicates the service should register itself with Eureka
    fetch-registry: true # Indicates the service should fetch the Eureka registry
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,env 
  endpoint:
    health:
      show-details: always    